---
title: 'FRI Data Entry SOP'
author:
  - Dan Ressler
  - Sara Ashcraft
  - Mark Newman
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FRI Data Entry SOP}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---


# Instructions

Read entire document before proceeding.
Data can be entered after surveys have been completed.
However, it is our suggestion to enter the Site information prior to the field season using the Events Form, then create a "Survey Cover Sheet see Reports > Survey Cover Sheet - Select Sites first.
This way you have your site data available in one place when scouting or surveying.
After entering all data on a field sheet, initial each page at the lower right to indicate your work.
Then when a survey packet is complete put a check ($\checkmark$) next to your initials on the survey cover sheet to indicate you have completed the packet.

Location: https://github.com/markanewman/dbfishR

Open the "Template.accdb" file for the data entry.
Save file with your last name or collaborator name in place of "Template".

Under Objects panels, navigate to Forms or Tables as needed.
